version: '3.8'

services:
  mysql-service:
    image: mysql:8.4
    container_name: Evologic
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Evologic
      MYSQL_USER: evologic
      MYSQL_PASSWORD: evologic
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress-service:
    image: wordpress:6
    container_name: wordpress-container
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: Evologic
      WORDPRESS_DB_USER: evologic
      WORDPRESS_DB_PASSWORD: evologic
      WORDPRESS_DB_NAME: evologic
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 50s
    restart: always
    depends_on:
      mysql-service:
        condition: service_healthy
volumes:
  mysql-data:
  wordpress-vol:

networks:
  net-wp:
    driver: bridge
